import React, { createContext, useContext, useState, useEffect } from 'react';
import { translationService } from '../services/translationService';

// Create Language Context
const LanguageContext = createContext();

// French translations (default)
const frenchTranslations = {
  // Navigation
  'nav.dashboard': 'Tableau de Bord',
  'nav.users': 'Utilisateurs',
  'nav.interventions': 'Interventions',
  'nav.workOrders': 'Bons de Travail',
  'nav.components': 'Composants',
  'nav.settings': 'Paramètres',
  'nav.profile': 'Profil',
  'nav.logout': 'Déconnexion',

  // Authentication
  'auth.login': 'Connexion',
  'auth.register': 'Inscription',
  'auth.secure_login': 'Connexion Sécurisée',
  'auth.email': 'Adresse Email',
  'auth.password': 'Mot de passe',
  'auth.logging_in': 'Connexion en cours...',
  'auth.login_button': 'Se Connecter',
  'auth.secure_ssl': 'Connexion sécurisée SSL',
  'auth.email': 'Email',
  'auth.password': 'Mot de passe',
  'auth.firstName': 'Prénom',
  'auth.lastName': 'Nom',
  'auth.role': 'Rôle',
  'auth.phone': 'Téléphone',
  'auth.address': 'Adresse',
  'auth.login.title': 'Connexion Sécurisée',
  'auth.login.subtitle': '🏢 Plateforme Sagemcom',
  'auth.login.button': '🚀 Se Connecter',
  'auth.register.title': 'Créer un Compte',
  'auth.register.subtitle': '🏢 Rejoignez la Plateforme Sagemcom',
  'auth.register.button': '🚀 Créer mon compte',
  'auth.register.success': 'Compte créé avec succès !',
  'auth.register.hasAccount': 'Déjà un compte ?',
  'auth.ssl': '🔒 Connexion SSL Sécurisée',

  // Work Orders (Bons de Travail)
  'workOrder.title': 'Bon de Travail',
  'workOrder.subtitle': 'Gestion des Bons de Travail',
  'workOrder.description': '📝 Description',
  'workOrder.dateCreation': '📅 Date Création',
  'workOrder.dateDebut': '🚀 Date Début',
  'workOrder.dateFin': '🏁 Date Fin',
  'workOrder.status': '📊 Statut',
  'workOrder.technician': '👨‍🔧 Technicien',
  'workOrder.components': '🔧 Composants',
  'workOrder.generate': 'Générer BT',
  'workOrder.close': 'Clôturer BT',
  'workOrder.search': 'Rechercher des composants...',
  'workOrder.instruction': 'Tapez pour rechercher et sélectionner des composants',
  'workOrder.success': 'Opération réussie !',
  'workOrder.error': 'Une erreur est survenue',
  'workOrder.list.title': 'Liste des Bons de Travail',
  'workOrder.list.subtitle': 'Gestion et Suivi des BT',

  // Interventions
  'intervention.title': 'Interventions',
  'intervention.subtitle': 'Gestion des Demandes d\'Intervention',
  'intervention.add.title': 'Nouvelle Intervention',
  'intervention.add.subtitle': 'Créer une Demande d\'Intervention',
  'intervention.add.button': '✨ Créer l\'Intervention',
  'intervention.type': 'Type',
  'intervention.priority': 'Priorité',
  'intervention.demandeur': 'Demandeur',
  'intervention.description': 'Description',
  'intervention.dateCreation': 'Date Création',
  'intervention.status': 'Statut',
  'intervention.actions': 'Actions',
  'intervention.success': 'Intervention créée avec succès !',
  'intervention.error': 'Erreur lors de la création',

  'interventions.title': 'Gestion des Interventions',
  'interventions.subtitle': 'Suivi et Gestion des Demandes d\'Intervention Sagemcom',
  'interventions.loading': 'Chargement des interventions...',
  'interventions.error': 'Erreur',
  'interventions.retry': 'Réessayer',
  'interventions.create': 'Créer une Intervention',
  'interventions.total': 'Total Interventions',
  'interventions.pending': 'En Attente',
  'interventions.in_progress': 'En Cours',
  'interventions.no_data': 'Aucune intervention trouvée',
  'interventions.no_data_desc': 'Commencez par créer votre première intervention.',
  'interventions.items_per_page': 'Éléments par page',
  'interventions.of': 'sur',
  'interventions.previous': 'Précédent',
  'interventions.next': 'Suivant',
  'interventions.create_title': 'Nouvelle Intervention',
  'interventions.title_field': 'Titre de l\'intervention',
  'interventions.title_placeholder': 'Ex: Réparation équipement réseau',
  'interventions.description_field': 'Description',
  'interventions.description_placeholder': 'Décrivez le problème et les actions nécessaires...',
  'interventions.priority_field': 'Priorité',
  'interventions.priority_low': 'Faible',
  'interventions.priority_normal': 'Normale',
  'interventions.priority_high': 'Haute',
  'interventions.priority_critical': 'Critique',
  'interventions.cancel': 'Annuler',
  'interventions.creating': 'Création...',
  'interventions.create_button': 'Créer l\'intervention',

  // Settings
  'settings.title': 'Paramètres Utilisateurs',
  'settings.subtitle': 'Gestion des Comptes et Permissions',
  'settings.filters': 'Filtres et Recherche',
  'settings.role.filter': 'Filtrer par rôle',
  'settings.search': 'Rechercher un utilisateur...',
  'settings.search.placeholder': 'Nom, prénom, email...',
  'settings.sort': 'Trier par',
  'settings.confirmation': 'Afficher seulement les confirmés',
  'settings.users.count': 'utilisateurs trouvés',
  'settings.edit': 'Modifier',
  'settings.delete': 'Supprimer',
  'settings.confirm': 'Confirmer',
  'settings.edit.title': 'Modifier Utilisateur',
  'settings.save': 'Sauvegarder',
  'settings.cancel': 'Annuler',
  'settings.success': 'Utilisateur modifié avec succès !',
  'settings.error': 'Erreur lors de la modification',
  'settings.delete.confirm': 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',
  'settings.delete.success': 'Utilisateur supprimé avec succès !',
  'settings.delete.error': 'Erreur lors de la suppression de l\'utilisateur',
  'settings.confirm.success': 'Utilisateur confirmé avec succès !',
  'settings.confirm.error': 'Erreur lors de la confirmation de l\'utilisateur',
  'settings.form.required': 'Veuillez remplir tous les champs obligatoires',
  'settings.stats.total': 'Total Utilisateurs',
  'settings.stats.admins': 'Administrateurs',
  'settings.stats.technicians': 'Techniciens',
  'settings.stats.unconfirmed': 'Non Confirmés',

  // Bon de Travail (Work Orders)
  'workorder.title': 'Bon de Travail',
  'workorder.subtitle': 'Gestion des Bons de Travail',
  'workorder.description': 'Description',
  'workorder.creation_date': 'Date de Création',
  'workorder.start_date': 'Date de Début',
  'workorder.end_date': 'Date de Fin',
  'workorder.status': 'Statut',
  'workorder.technician': 'Technicien',
  'workorder.components': 'Composants',
  'workorder.status.pending': 'En Attente',
  'workorder.status.in_progress': 'En Cours',
  'workorder.status.completed': 'Terminé',
  'workorder.status.cancelled': 'Annulé',
  'workorder.generate': 'Générer le BT',
  'workorder.close': 'Fermer le BT',
  'workorder.select_technician': 'Sélectionner un technicien',
  'workorder.search_components': 'Rechercher des composants...',
  'workorder.add_component': 'Ajouter Composant',
  'workorder.remove_component': 'Retirer',
  'workorder.success': 'Opération réussie !',
  'workorder.error': 'Une erreur s\'est produite',
  'workorder.description.placeholder': 'Décrivez les travaux à effectuer...',
  'workorder.select_components': 'Sélectionner les composants',
  'workorder.form.required': 'Veuillez remplir tous les champs obligatoires',

  // Dashboard
  'dashboard.title': 'Tableau de Bord',
  'dashboard.subtitle': 'Vue d\'ensemble des activités',
  'dashboard.welcome': 'Bienvenue sur votre tableau de bord',

  // Profile
  'profile.title': 'Mon Profil',
  'profile.subtitle': 'Gestion du profil utilisateur',
  'profile.edit': 'Modifier le profil',
  'profile.save': 'Sauvegarder',
  'profile.cancel': 'Annuler',
  'profile.firstName': 'Prénom',
  'profile.lastName': 'Nom',
  'profile.email': 'Email',
  'profile.phone': 'Téléphone',
  'profile.address': 'Adresse',
  'profile.role': 'Rôle',
  'profile.loading': 'Chargement du profil...',
  'profile.error': 'Erreur lors du chargement',
  'profile.success': 'Profil mis à jour avec succès',
  'profile.personal_info': 'Informations personnelles',
  'profile.contact_info': 'Informations de contact',
  'profile.account_info': 'Informations du compte',
  'profile.firstName.placeholder': 'Votre prénom',
  'profile.lastName.placeholder': 'Votre nom de famille',
  'profile.phone.placeholder': '+33 1 23 45 67 89',
  'profile.address.placeholder': '123 Rue de la République, 75001 Paris',

  // Common
  'common.loading': 'Chargement...',
  'common.error': 'Erreur',
  'common.success': 'Succès',
  'common.cancel': 'Annuler',
  'common.save': 'Enregistrer',
  'common.delete': 'Supprimer',
  'common.edit': 'Modifier',
  'common.add': 'Ajouter',
  'common.search': 'Rechercher',
  'common.filter': 'Filtrer',
  'common.sort': 'Trier',
  'common.actions': 'Actions',
  'common.status': 'Statut',
  'common.date': 'Date',
  'common.name': 'Nom',
  'common.email': 'Email',
  'common.role': 'Rôle',
  'common.phone': 'Téléphone',
  'common.address': 'Adresse',
  'common.description': 'Description',
  'common.type': 'Type',
  'common.priority': 'Priorité',
  'common.close': 'Fermer',
  'common.open': 'Ouvrir',
  'common.view': 'Voir',
  'common.download': 'Télécharger',
  'common.upload': 'Téléverser',
  'common.next': 'Suivant',
  'common.previous': 'Précédent',
  'common.page': 'Page',
  'common.of': 'sur',
  'common.items': 'éléments',
  'common.per.page': 'par page',

  // Sidebar
  'sidebar.title': 'Sagemcom Maintenance',
  'sidebar.subtitle': 'Plateforme Professionnelle',
  'sidebar.secure_connection': 'Connexion Sécurisée',
  'sidebar.dashboard': 'Dashboard',
  'sidebar.profile': 'Mon Profil',
  'sidebar.projects': 'Projets',
  'sidebar.subprojects': 'Sous-projets',
  'sidebar.interventions': 'Interventions',
  'sidebar.add_intervention': 'Ajouter Intervention',
  'sidebar.work_orders': 'Liste des Bons de Travail',
  'sidebar.work_order': 'Bon de Travail',
  'sidebar.components': 'Composants',
  'sidebar.validation_orders': 'Validation Commandes Moderne',
  'sidebar.warehouse_dashboard': 'Dashboard Magasinier',
  'sidebar.planning': 'Planning',
  'sidebar.calendar': 'Calendrier',
  'sidebar.analytics': 'Analytics Dashboard',
  'sidebar.predictive_kpi': 'KPI Prédictif',
  'sidebar.enhanced_analytics': 'Analytics Avancé',
  'sidebar.advanced_analytics': 'Analytics IA Avancé',
  'sidebar.notifications_center': 'Centre Notifications',
  'sidebar.test_system': 'Test Système',
  'sidebar.mobile_app': 'App Mobile Techniciens',
  'sidebar.intelligent_scheduler': 'Planificateur Intelligent',
  'sidebar.gamification': 'Gamification',
  'sidebar.ai_assistant': 'Assistant IA',
  'sidebar.user_management': 'Gestion des Utilisateurs',
  'sidebar.integration_test': 'Test d\'Intégration',
  'sidebar.section.dashboard': 'Dashboard',
  'sidebar.section.project_management': 'Gestion de Projets',
  'sidebar.section.interventions': 'Gestion des Interventions',
  'sidebar.section.components': 'Gestion des Composants',
  'sidebar.section.planning': 'Planning & Calendrier',
  'sidebar.section.analytics': 'Analytics & Rapports',
  'sidebar.section.notifications': 'Notifications',
  'sidebar.section.mobile': 'Modules Mobiles',
  'sidebar.section.gamification': 'Gamification & IA',
  'sidebar.section.administration': 'Administration',

  // Roles
  'role.admin': 'Administrateur',
  'role.magasinier': 'Magasinier',
  'role.chef.secteur': 'Chef de Secteur',
  'role.technicien.curatif': 'Technicien Curatif',
  'role.technicien.preventif': 'Technicien Préventif',

  // Status
  'status.pending': 'En attente',
  'status.in.progress': 'En cours',
  'status.completed': 'Terminé',
  'status.cancelled': 'Annulé',
  'status.confirmed': 'Confirmé',
  'status.unconfirmed': 'Non confirmé',

  // Landing Page
  'landing.hero.title': 'Plateforme de Gestion de Maintenance Sagemcom',
  'landing.hero.description': 'Gérez efficacement les interventions curatives et préventives, le stock des pièces de rechange, le planning des techniciens et les indicateurs de performance. Optimisez la maintenance grâce à une interface intuitive.',
  'landing.hero.button': 'Commencer',
  'landing.features.title': 'Fonctionnalités principales',
  'landing.features.subtitle': 'Une solution complète pour la gestion de la maintenance industrielle.',
  'landing.features.access': 'Accéder',
  'landing.features.users.title': 'Gestion des utilisateurs',
  'landing.features.users.description': 'Connexion sécurisée, attribution de rôles, gestion des comptes.',
  'landing.features.interventions.title': 'Interventions',
  'landing.features.interventions.description': 'Création, planification et suivi des DI curatives/préventives.',
  'landing.features.workOrders.title': 'Bon de travail',
  'landing.features.workOrders.description': 'Génération automatique à partir des DI, suivi de l\'exécution.',
  'landing.features.stock.title': 'Stock & PDR',
  'landing.features.stock.description': 'Commandes, seuils critiques, validation par le magasinier.',
  'landing.features.kpi.title': 'Indicateurs & KPI',
  'landing.features.kpi.description': 'Taux d\'exécution, MTTR, MTBF, performance des techniciens.',
  'landing.features.planning.title': 'Planning Techniciens',
  'landing.features.planning.description': 'Disponibilités, affectations et conflits évités automatiquement.',
  'landing.kpi.title': 'Indicateurs de Performance',
  'landing.kpi.mttr': 'MTTR',
  'landing.kpi.mtbf': 'MTBF',
  'landing.kpi.execution': 'Taux d\'exécution',
  'landing.kpi.stock': 'Rupture Stock',
  'landing.why.title': 'Pourquoi choisir notre plateforme ?',
  'landing.why.feature1': 'Interface intuitive adaptée à tous les rôles',
  'landing.why.feature2': 'Suivi en temps réel des interventions',
  'landing.why.feature3': 'Automatisation des bons de travail',
  'landing.why.feature4': 'Calcul automatique des KPI',
  'landing.why.demo': 'Demander une démo',

  // Profile Page
  'profile.connect': 'Se connecter',
  'profile.friends': 'Amis',
  'profile.photos': 'Photos',
  'profile.comments': 'Commentaires',
  'profile.name': 'Jenna Stones',
  'profile.location': 'Los Angeles, Californie',
  'profile.job': 'Gestionnaire de Solutions - Responsable Creative Tim',
  'profile.education': 'Université d\'Informatique',
  'profile.bio': 'Artiste aux talents variés, Jenna, nom adopté par Nick Murphy, né à Melbourne et basé à Brooklyn, écrit, interprète et enregistre toute sa propre musique, lui donnant une sensation chaleureuse et intime avec une structure rythmique solide. Un artiste aux talents considérables.',
  'profile.show_more': 'Voir plus',

  // Index Page
  'index.hero.title': 'Gestion de',
  'index.hero.title2': 'maintenance',
  'index.hero.subtitle': 'Optimisez vos opérations efficacement',
  'index.hero.cta': 'VOIR LES SERVICES',
  'index.about.badge': 'OPTIMISEZ VOTRE MAINTENANCE',
  'index.about.title': 'Une solution complète pour votre gestion',
  'index.about.description': 'Simplifiez la gestion de vos opérations de maintenance avec Sagemcom. Notre plateforme intelligente vous permet d\'optimiser vos processus, réduire les temps d\'arrêt et améliorer l\'efficacité de vos équipes.',
  'index.about.contact': 'Nous contacter',
  'index.about.image_alt': 'Dashboard maintenance industrielle',
  'index.services.title': 'MAINTENANCE OPTIMISÉE',
  'index.services.subtitle': 'Gérez vos opérations en toute simplicité',
  'index.services.card1.title': 'Gestion des données matérielles',
  'index.services.card1.description': 'Optimisez la gestion de vos ressources matérielles avec un suivi complet et une traçabilité avancée.',
  'index.services.card2.title': 'Planification des interventions',
  'index.services.card2.description': 'Améliorez votre efficacité avec notre planification intelligente et automatisée des interventions.',
  'index.services.card3.title': 'Suivi des stocks de pièces de rechange',
  'index.services.card3.description': 'Gérez vos stocks de manière optimale et évitez les ruptures avec notre système intelligent.',
  'index.operations.title': 'SIMPLIFIEZ VOTRE MAINTENANCE',
  'index.operations.subtitle': 'Gérez efficacement vos opérations au quotidien.',
  'index.operations.users.title': 'Gestion des utilisateurs',
  'index.operations.users.description': 'Optimisez la collaboration en gérant efficacement vos utilisateurs.',
  'index.operations.interventions.title': 'Suivi des interventions',
  'index.operations.interventions.description': 'Suivez toutes vos interventions pour une maintenance optimisée.',
  'index.operations.stock.title': 'Gestion des stocks',
  'index.operations.stock.description': 'Maîtrisez vos stocks de pièces pour une maintenance efficace.',
  'index.operations.kpi.title': 'Analyse des KPI',
  'index.operations.kpi.description': 'Analysez vos performances avec des indicateurs précis et détaillés.',
  'index.operations.learn_more': 'En savoir plus',

  // Languages
  'language.french': 'Français',
  'language.english': 'English',
  'language.arabic': 'العربية',
  'language.select': 'Choisir la langue'
};

// English translations
const englishTranslations = {
  // Navigation
  'nav.dashboard': 'Dashboard',
  'nav.users': 'Users',
  'nav.interventions': 'Interventions',
  'nav.workOrders': 'Work Orders',
  'nav.components': 'Components',
  'nav.settings': 'Settings',
  'nav.profile': 'Profile',
  'nav.logout': 'Logout',

  // Sidebar
  'sidebar.title': 'Sagemcom Maintenance',
  'sidebar.subtitle': 'Professional Platform',
  'sidebar.secure_connection': 'Secure Connection',
  'sidebar.section.dashboard': '🏠 Dashboard',
  'sidebar.section.project_management': '📈 Project Management',
  'sidebar.section.interventions': '🔧 Intervention Management',
  'sidebar.section.components': '📦 Component Management',
  'sidebar.section.planning': '📅 Planning & Calendar',
  'sidebar.section.analytics': '📈 Analytics & Reports',
  'sidebar.section.notifications': '🔔 Notifications',
  'sidebar.section.mobile': '📱 Mobile Modules',
  'sidebar.section.gamification': '🎮 Gamification & AI',
  'sidebar.section.administration': '⚙️ Administration',
  'sidebar.dashboard': 'Dashboard',
  'sidebar.profile': 'My Profile',
  'sidebar.projects': 'Projects',
  'sidebar.subprojects': 'Sub-projects',
  'sidebar.interventions': 'Interventions',
  'sidebar.add_intervention': 'Add Intervention',
  'sidebar.work_orders': 'Work Orders List',
  'sidebar.work_order': 'Work Order',
  'sidebar.components': 'Components',
  'sidebar.validation_orders': 'Modern Order Validation',
  'sidebar.warehouse_dashboard': 'Warehouse Dashboard',
  'sidebar.planning': 'Planning',
  'sidebar.calendar': 'Calendar',
  'sidebar.analytics': 'Analytics Dashboard',
  'sidebar.predictive_kpi': 'Predictive KPI',
  'sidebar.enhanced_analytics': 'Advanced Analytics',
  'sidebar.advanced_analytics': 'Advanced AI Analytics',
  'sidebar.notifications_center': 'Notifications Center',
  'sidebar.test_system': 'System Test',
  'sidebar.mobile_app': 'Technician Mobile App',
  'sidebar.intelligent_scheduler': 'Intelligent Scheduler',
  'sidebar.gamification': 'Gamification',
  'sidebar.ai_assistant': 'AI Assistant',
  'sidebar.user_management': 'User Management',
  'sidebar.integration_test': 'Integration Test',

  // Interventions page
  'interventions.title': 'Intervention Management',
  'interventions.subtitle': 'Sagemcom Intervention Request Tracking and Management',
  'interventions.loading': 'Loading interventions...',
  'interventions.error': 'Error',
  'interventions.retry': 'Retry',
  'interventions.create': 'Create Intervention',
  'interventions.total': 'Total Interventions',
  'interventions.pending': 'Pending',
  'interventions.in_progress': 'In Progress',
  'interventions.no_data': 'No interventions found',
  'interventions.no_data_desc': 'Start by creating your first intervention.',
  'interventions.items_per_page': 'Items per page',
  'interventions.of': 'of',
  'interventions.previous': 'Previous',
  'interventions.next': 'Next',
  'interventions.create_title': 'New Intervention',
  'interventions.title_field': 'Intervention Title',
  'interventions.title_placeholder': 'Ex: Network equipment repair',
  'interventions.description_field': 'Description',
  'interventions.description_placeholder': 'Describe the problem and necessary actions...',
  'interventions.priority_field': 'Priority',
  'interventions.priority_low': 'Low',
  'interventions.priority_normal': 'Normal',
  'interventions.priority_high': 'High',
  'interventions.priority_critical': 'Critical',
  'interventions.cancel': 'Cancel',
  'interventions.creating': 'Creating...',
  'interventions.create_button': 'Create intervention',
  'intervention.error.loading': 'Error loading interventions',

  // Authentication
  'auth.login': 'Login',
  'auth.register': 'Register',
  'auth.secure_login': 'Secure Login',
  'auth.email': 'Email Address',
  'auth.password': 'Password',
  'auth.logging_in': 'Logging in...',
  'auth.login_button': 'Login',
  'auth.secure_ssl': 'Secure SSL Connection',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.firstName': 'First Name',
  'auth.lastName': 'Last Name',
  'auth.role': 'Role',
  'auth.phone': 'Phone',
  'auth.address': 'Address',
  'auth.login.title': 'Secure Login',
  'auth.login.subtitle': '🏢 Sagemcom Platform',
  'auth.login.button': '🚀 Sign In',
  'auth.register.title': 'Create Account',
  'auth.register.subtitle': '🏢 Join Sagemcom Platform',
  'auth.register.button': '🚀 Create Account',
  'auth.register.success': 'Account created successfully!',
  'auth.register.hasAccount': 'Already have an account?',
  'auth.ssl': '🔒 Secure SSL Connection',

  // Work Orders
  'workOrder.title': 'Work Order',
  'workOrder.subtitle': 'Work Order Management',
  'workOrder.description': '📝 Description',
  'workOrder.dateCreation': '📅 Creation Date',
  'workOrder.dateDebut': '🚀 Start Date',
  'workOrder.dateFin': '🏁 End Date',
  'workOrder.status': '📊 Status',
  'workOrder.technician': '👨‍🔧 Technician',
  'workOrder.components': '🔧 Components',
  'workOrder.generate': 'Generate WO',
  'workOrder.close': 'Close WO',
  'workOrder.search': 'Search components...',
  'workOrder.instruction': 'Type to search and select components',
  'workOrder.success': 'Operation successful!',
  'workOrder.error': 'An error occurred',
  'workOrder.list.title': 'Work Orders List',
  'workOrder.list.subtitle': 'WO Management and Tracking',

  // Interventions
  'intervention.title': 'Interventions',
  'intervention.subtitle': 'Intervention Request Management',
  'intervention.add.title': 'New Intervention',
  'intervention.add.subtitle': 'Create Intervention Request',
  'interventions.add_button': 'إضافة تدخل',
  'interventions.cancel_button': 'إلغاء',
  'interventions.description_field': 'الوصف',
  'interventions.description_placeholder': 'صف التدخل المطلوب بالتفصيل...',
  'interventions.priority_field': 'الأولوية',
  'interventions.priority_low': 'منخفضة',
  'interventions.priority_normal': 'متوسطة',
  'interventions.priority_high': 'عالية',
  'intervention.requester': 'مقدم الطلب',
  'intervention.failure': 'وصف العطل',
  'intervention.failure.placeholder': 'صف العطل المُلاحظ...',
  'intervention.urgent': 'تدخل عاجل',
  'intervention.frequency': 'التكرار',
  'intervention.next_appointment': 'الموعد القادم',
  'intervention.type_title': 'نوع التدخل',
  'intervention.general_info': 'المعلومات العامة',
  'intervention.failure_details': 'تفاصيل العطل',
  'intervention.maintenance_details': 'تفاصيل الصيانة',
  'intervention.create_button': 'إنشاء التدخل',
  'intervention.type_curative': 'علاجي',
  'intervention.type_preventive': 'وقائي',
  'intervention.type_curative_desc': 'إصلاح بعد عطل',
  'intervention.type_preventive_desc': 'صيانة مجدولة',
  'intervention.select_requester': 'اختر مقدم الطلب',
  'intervention.creating': 'جاري الإنشاء...',
  'intervention.frequency.select': 'اختر',
  'intervention.frequency.weekly': 'أسبوعي',
  'intervention.frequency.monthly': 'شهري',
  'intervention.frequency.quarterly': 'ربع سنوي',
  'intervention.frequency.biannual': 'نصف سنوي',
  'intervention.frequency.annual': 'سنوي',
  'schedule.weekly_title': 'الجدول الأسبوعي',
  'interventions.description_field': 'Description',
  'interventions.description_placeholder': 'Describe the required intervention in detail...',
  'interventions.priority_field': 'Priority',
  'interventions.priority_low': 'Low',
  'interventions.priority_normal': 'Medium',
  'interventions.priority_high': 'High',
  'intervention.requester': 'Requester',
  'intervention.failure': 'Failure Description',
  'intervention.failure.placeholder': 'Describe the observed failure...',
  'intervention.urgent': 'Urgent intervention',
  'intervention.frequency': 'Frequency',
  'intervention.next_appointment': 'Next Appointment',
  'intervention.type_title': 'Intervention Type',
  'intervention.general_info': 'General Information',
  'intervention.failure_details': 'Failure Details',
  'intervention.maintenance_details': 'Maintenance Details',
  'intervention.create_button': 'Create Intervention',
  'intervention.type_curative': 'Curative',
  'intervention.type_preventive': 'Preventive',
  'intervention.type_curative_desc': 'Repair following a breakdown',
  'intervention.type_preventive_desc': 'Scheduled maintenance',
  'intervention.select_requester': 'Select a requester',
  'intervention.creating': 'Creating...',
  'intervention.frequency.select': 'Select',
  'intervention.frequency.weekly': 'Weekly',
  'intervention.frequency.monthly': 'Monthly',
  'intervention.frequency.quarterly': 'Quarterly',
  'intervention.frequency.biannual': 'Biannual',
  'intervention.frequency.annual': 'Annual',
  'schedule.weekly_title': 'Weekly Schedule',
  'intervention.description_field': 'Description',
  'intervention.description_placeholder': 'Décrivez en détail l\'intervention nécessaire...',
  'intervention.priority_field': 'Priorité',
  'intervention.priority_low': 'Basse',
  'intervention.priority_normal': 'Moyenne',
  'intervention.priority_high': 'Haute',
  'intervention.requester': 'Demandeur',
  'intervention.failure': 'Description de la Panne',
  'intervention.failure.placeholder': 'Décrivez la panne observée...',
  'intervention.urgent': 'Intervention urgente',
  'intervention.frequency': 'Fréquence',
  'intervention.next_appointment': 'Prochain RDV',
  'intervention.type_title': 'Type d\'Intervention',
  'intervention.general_info': 'Informations Générales',
  'intervention.failure_details': 'Détails de la Panne',
  'intervention.maintenance_details': 'Détails de la Maintenance',
  'intervention.create_button': 'Créer l\'Intervention',
  'intervention.type_curative': 'Curative',
  'intervention.type_preventive': 'Préventive',
  'intervention.type_curative_desc': 'Réparation suite à une panne',
  'intervention.type_preventive_desc': 'Maintenance programmée',
  'intervention.select_requester': 'Sélectionner un demandeur',
  'intervention.creating': 'Création en cours...',
  'intervention.frequency.select': 'Sélectionner',
  'intervention.frequency.weekly': 'Hebdomadaire',
  'intervention.frequency.monthly': 'Mensuelle',
  'intervention.frequency.quarterly': 'Trimestrielle',
  'intervention.frequency.biannual': 'Semestrielle',
  'intervention.frequency.annual': 'Annuelle',
  'schedule.weekly_title': 'Emploi du Temps Hebdomadaire',
  'intervention.priority': 'Priority',
  'intervention.demandeur': 'Requester',
  'intervention.description': 'Description',
  'intervention.dateCreation': 'Creation Date',
  'intervention.status': 'Status',
  'intervention.actions': 'Actions',
  'intervention.success': 'Intervention created successfully!',
  'intervention.error': 'Error creating intervention',

  // Settings
  'settings.title': 'User Settings',
  'settings.subtitle': 'Account and Permission Management',
  'settings.filters': 'Filters and Search',
  'settings.role.filter': 'Filter by role',
  'settings.search': 'Search for a user...',
  'settings.search.placeholder': 'Name, first name, email...',
  'settings.sort': 'Sort by',
  'settings.confirmation': 'Show only confirmed',
  'settings.users.count': 'users found',
  'settings.edit': 'Edit',
  'settings.delete': 'Delete',
  'settings.confirm': 'Confirm',
  'settings.edit.title': 'Edit User',
  'settings.save': 'Save',
  'settings.cancel': 'Cancel',
  'settings.success': 'User updated successfully!',
  'settings.error': 'Error updating user',
  'settings.delete.confirm': 'Are you sure you want to delete this user?',
  'settings.delete.success': 'User deleted successfully!',
  'settings.delete.error': 'Error deleting user',
  'settings.confirm.success': 'User confirmed successfully!',
  'settings.confirm.error': 'Error confirming user',
  'settings.form.required': 'Please fill in all required fields',
  'settings.stats.total': 'Total Users',
  'settings.stats.admins': 'Administrators',
  'settings.stats.technicians': 'Technicians',
  'settings.stats.unconfirmed': 'Unconfirmed',

  // Work Orders
  'workorder.title': 'Work Order',
  'workorder.subtitle': 'Work Order Management',
  'workorder.description': 'Description',
  'workorder.creation_date': 'Creation Date',
  'workorder.start_date': 'Start Date',
  'workorder.end_date': 'End Date',
  'workorder.status': 'Status',
  'workorder.technician': 'Technician',
  'workorder.components': 'Components',
  'workorder.status.pending': 'Pending',
  'workorder.status.in_progress': 'In Progress',
  'workorder.status.completed': 'Completed',
  'workorder.status.cancelled': 'Cancelled',
  'workorder.generate': 'Generate WO',
  'workorder.close': 'Close WO',
  'workorder.select_technician': 'Select a technician',
  'workorder.search_components': 'Search components...',
  'workorder.add_component': 'Add Component',
  'workorder.remove_component': 'Remove',
  'workorder.success': 'Operation successful!',
  'workorder.error': 'An error occurred',
  'workorder.description.placeholder': 'Describe the work to be performed...',
  'workorder.select_components': 'Select components',
  'workorder.form.required': 'Please fill in all required fields',

  // Dashboard
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Activity Overview',
  'dashboard.welcome': 'Welcome to your dashboard',

  // Profile
  'profile.title': 'My Profile',
  'profile.subtitle': 'User profile management',
  'profile.edit': 'Edit profile',
  'profile.save': 'Save',
  'profile.cancel': 'Cancel',
  'profile.firstName': 'First Name',
  'profile.lastName': 'Last Name',
  'profile.email': 'Email',
  'profile.phone': 'Phone',
  'profile.address': 'Address',
  'profile.role': 'Role',
  'profile.loading': 'Loading profile...',
  'profile.error': 'Error loading profile',
  'profile.success': 'Profile updated successfully',
  'profile.personal_info': 'Personal Information',
  'profile.contact_info': 'Contact Information',
  'profile.account_info': 'Account Information',
  'profile.firstName.placeholder': 'Your first name',
  'profile.lastName.placeholder': 'Your last name',
  'profile.phone.placeholder': '+1 234 567 8900',
  'profile.address.placeholder': '123 Main Street, City, State 12345',

  // Common
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.sort': 'Sort',
  'common.actions': 'Actions',
  'common.status': 'Status',
  'common.date': 'Date',
  'common.name': 'Name',
  'common.email': 'Email',
  'common.role': 'Role',
  'common.phone': 'Phone',
  'common.address': 'Address',
  'common.description': 'Description',
  'common.type': 'Type',
  'common.priority': 'Priority',
  'common.close': 'Close',
  'common.open': 'Open',
  'common.view': 'View',
  'common.download': 'Download',
  'common.upload': 'Upload',
  'common.next': 'Next',
  'common.previous': 'Previous',
  'common.page': 'Page',
  'common.of': 'of',
  'common.items': 'items',
  'common.per.page': 'per page',

  // Roles
  'role.admin': 'Administrator',
  'role.magasinier': 'Warehouse Manager',
  'role.chef.secteur': 'Sector Chief',
  'role.technicien.curatif': 'Curative Technician',
  'role.technicien.preventif': 'Preventive Technician',

  // Status
  'status.pending': 'Pending',
  'status.in.progress': 'In Progress',
  'status.completed': 'Completed',
  'status.cancelled': 'Cancelled',
  'status.confirmed': 'Confirmed',
  'status.unconfirmed': 'Unconfirmed',

  // Landing Page
  'landing.hero.title': 'Sagemcom Maintenance Management Platform',
  'landing.hero.description': 'Efficiently manage curative and preventive interventions, spare parts inventory, technician scheduling and performance indicators. Optimize maintenance through an intuitive interface.',
  'landing.hero.button': 'Get Started',
  'landing.features.title': 'Key Features',
  'landing.features.subtitle': 'A complete solution for industrial maintenance management.',
  'landing.features.access': 'Access',
  'landing.features.users.title': 'User Management',
  'landing.features.users.description': 'Secure login, role assignment, account management.',
  'landing.features.interventions.title': 'Interventions',
  'landing.features.interventions.description': 'Creation, planning and tracking of curative/preventive interventions.',
  'landing.features.workOrders.title': 'Work Orders',
  'landing.features.workOrders.description': 'Automatic generation from interventions, execution tracking.',
  'landing.features.stock.title': 'Stock & Spare Parts',
  'landing.features.stock.description': 'Orders, critical thresholds, warehouse manager validation.',
  'landing.features.kpi.title': 'Indicators & KPI',
  'landing.features.kpi.description': 'Execution rate, MTTR, MTBF, technician performance.',
  'landing.features.planning.title': 'Technician Planning',
  'landing.features.planning.description': 'Availability, assignments and conflicts automatically avoided.',
  'landing.kpi.title': 'Performance Indicators',
  'landing.kpi.mttr': 'MTTR',
  'landing.kpi.mtbf': 'MTBF',
  'landing.kpi.execution': 'Execution Rate',
  'landing.kpi.stock': 'Stock Shortage',
  'landing.why.title': 'Why choose our platform?',
  'landing.why.feature1': 'Intuitive interface adapted to all roles',
  'landing.why.feature2': 'Real-time intervention tracking',
  'landing.why.feature3': 'Work order automation',
  'landing.why.feature4': 'Automatic KPI calculation',
  'landing.why.demo': 'Request a Demo',

  // Profile Page
  'profile.connect': 'Connect',
  'profile.friends': 'Friends',
  'profile.photos': 'Photos',
  'profile.comments': 'Comments',
  'profile.name': 'Jenna Stones',
  'profile.location': 'Los Angeles, California',
  'profile.job': 'Solution Manager - Creative Tim Officer',
  'profile.education': 'University of Computer Science',
  'profile.bio': 'An artist of considerable range, Jenna the name taken by Melbourne-raised, Brooklyn-based Nick Murphy writes, performs and records all of his own music, giving it a warm, intimate feel with a solid groove structure. An artist of considerable range.',
  'profile.show_more': 'Show more',

  // Index Page
  'index.hero.title': 'Management of',
  'index.hero.title2': 'maintenance',
  'index.hero.subtitle': 'Optimize your operations efficiently',
  'index.hero.cta': 'VIEW SERVICES',
  'index.about.badge': 'OPTIMIZE YOUR MAINTENANCE',
  'index.about.title': 'A complete solution for your management',
  'index.about.description': 'Simplify the management of your maintenance operations with Sagemcom. Our intelligent platform allows you to optimize your processes, reduce downtime and improve the efficiency of your teams.',
  'index.about.contact': 'Get in touch',
  'index.about.image_alt': 'Industrial maintenance dashboard',
  'index.services.title': 'OPTIMIZED MAINTENANCE',
  'index.services.subtitle': 'Manage your operations with ease',
  'index.services.card1.title': 'Material data management',
  'index.services.card1.description': 'Optimize the management of your material resources with complete tracking and advanced traceability.',
  'index.services.card2.title': 'Intervention planning',
  'index.services.card2.description': 'Improve your efficiency with our intelligent and automated intervention planning.',
  'index.services.card3.title': 'Spare parts inventory tracking',
  'index.services.card3.description': 'Manage your inventory optimally and avoid stockouts with our intelligent system.',
  'index.operations.title': 'SIMPLIFY YOUR MAINTENANCE',
  'index.operations.subtitle': 'Efficiently manage your daily operations.',
  'index.operations.users.title': 'User management',
  'index.operations.users.description': 'Optimize collaboration by efficiently managing your users.',
  'index.operations.interventions.title': 'Intervention tracking',
  'index.operations.interventions.description': 'Track all your interventions for optimized maintenance.',
  'index.operations.stock.title': 'Inventory management',
  'index.operations.stock.description': 'Master your parts inventory for efficient maintenance.',
  'index.operations.kpi.title': 'KPI Analysis',
  'index.operations.kpi.description': 'Analyze your performance with precise and detailed indicators.',
  'index.operations.learn_more': 'Learn more',

  // Languages
  'language.french': 'Français',
  'language.english': 'English',
  'language.arabic': 'العربية',
  'language.select': 'Select Language'
};

// Arabic translations
const arabicTranslations = {
  // Navigation
  'nav.dashboard': 'لوحة التحكم',
  'nav.users': 'المستخدمون',
  'nav.interventions': 'التدخلات',
  'nav.workOrders': 'أوامر العمل',
  'nav.components': 'المكونات',
  'nav.settings': 'الإعدادات',
  'nav.profile': 'الملف الشخصي',
  'nav.logout': 'تسجيل الخروج',

  // Sidebar
  'sidebar.title': 'صيانة ساجيمكوم',
  'sidebar.subtitle': 'منصة مهنية',
  'sidebar.secure_connection': 'اتصال آمن',
  'sidebar.section.dashboard': '🏠 لوحة التحكم',
  'sidebar.section.project_management': '📈 إدارة المشاريع',
  'sidebar.section.interventions': '🔧 إدارة التدخلات',
  'sidebar.section.components': '📦 إدارة المكونات',
  'sidebar.section.planning': '📅 التخطيط والتقويم',
  'sidebar.section.analytics': '📈 التحليلات والتقارير',
  'sidebar.section.notifications': '🔔 الإشعارات',
  'sidebar.section.mobile': '📱 الوحدات المحمولة',
  'sidebar.section.gamification': '🎮 التلعيب والذكاء الاصطناعي',
  'sidebar.section.administration': '⚙️ الإدارة',
  'sidebar.dashboard': 'لوحة التحكم',
  'sidebar.profile': 'ملفي الشخصي',
  'sidebar.projects': 'المشاريع',
  'sidebar.subprojects': 'المشاريع الفرعية',
  'sidebar.interventions': 'التدخلات',
  'sidebar.add_intervention': 'إضافة تدخل',
  'sidebar.work_orders': 'قائمة أوامر العمل',
  'sidebar.work_order': 'أمر العمل',
  'sidebar.components': 'المكونات',
  'sidebar.validation_orders': 'التحقق من الطلبات الحديثة',
  'sidebar.warehouse_dashboard': 'لوحة تحكم المستودع',
  'sidebar.planning': 'التخطيط',
  'sidebar.calendar': 'التقويم',
  'sidebar.analytics': 'لوحة تحكم التحليلات',
  'sidebar.predictive_kpi': 'مؤشرات الأداء التنبؤية',
  'sidebar.enhanced_analytics': 'التحليلات المتقدمة',
  'sidebar.advanced_analytics': 'التحليلات المتقدمة بالذكاء الاصطناعي',
  'sidebar.notifications_center': 'مركز الإشعارات',
  'sidebar.test_system': 'اختبار النظام',
  'sidebar.mobile_app': 'تطبيق الفنيين المحمول',
  'sidebar.intelligent_scheduler': 'المجدول الذكي',
  'sidebar.gamification': 'التلعيب',
  'sidebar.ai_assistant': 'مساعد الذكاء الاصطناعي',
  'sidebar.user_management': 'إدارة المستخدمين',
  'sidebar.integration_test': 'اختبار التكامل',

  // Interventions page
  'interventions.title': 'إدارة التدخلات',
  'interventions.subtitle': 'تتبع وإدارة طلبات التدخل في ساجيمكوم',
  'interventions.loading': 'جاري تحميل التدخلات...',
  'interventions.error': 'خطأ',
  'interventions.retry': 'إعادة المحاولة',
  'interventions.create': 'إنشاء تدخل',
  'interventions.total': 'إجمالي التدخلات',
  'interventions.pending': 'في الانتظار',
  'interventions.in_progress': 'قيد التنفيذ',
  'interventions.no_data': 'لم يتم العثور على تدخلات',
  'interventions.no_data_desc': 'ابدأ بإنشاء تدخلك الأول.',
  'interventions.items_per_page': 'عناصر لكل صفحة',
  'interventions.of': 'من',
  'interventions.previous': 'السابق',
  'interventions.next': 'التالي',
  'interventions.create_title': 'تدخل جديد',
  'interventions.title_field': 'عنوان التدخل',
  'interventions.title_placeholder': 'مثال: إصلاح معدات الشبكة',
  'interventions.description_field': 'الوصف',
  'interventions.description_placeholder': 'صف المشكلة والإجراءات اللازمة...',
  'interventions.priority_field': 'الأولوية',
  'interventions.priority_low': 'منخفضة',
  'interventions.priority_normal': 'عادية',
  'interventions.priority_high': 'عالية',
  'interventions.priority_critical': 'حرجة',
  'interventions.cancel': 'إلغاء',
  'interventions.creating': 'جاري الإنشاء...',
  'interventions.create_button': 'إنشاء التدخل',
  'intervention.error.loading': 'خطأ في تحميل التدخلات',

  // Settings
  'settings.title': 'إعدادات المستخدمين',
  'settings.subtitle': 'إدارة الحسابات والصلاحيات',
  'settings.filters': 'المرشحات والبحث',
  'settings.role.filter': 'تصفية حسب الدور',
  'settings.search': 'البحث عن مستخدم...',
  'settings.search.placeholder': 'الاسم، الاسم الأول، البريد الإلكتروني...',
  'settings.sort': 'ترتيب حسب',
  'settings.confirmation': 'إظهار المؤكدين فقط',
  'settings.users.count': 'مستخدمين موجودين',
  'settings.edit': 'تعديل',
  'settings.delete': 'حذف',
  'settings.confirm': 'تأكيد',
  'settings.edit.title': 'تعديل المستخدم',
  'settings.save': 'حفظ',
  'settings.cancel': 'إلغاء',
  'settings.success': 'تم تحديث المستخدم بنجاح!',
  'settings.error': 'خطأ في تحديث المستخدم',
  'settings.delete.confirm': 'هل أنت متأكد من حذف هذا المستخدم؟',
  'settings.delete.success': 'تم حذف المستخدم بنجاح!',
  'settings.delete.error': 'خطأ في حذف المستخدم',
  'settings.confirm.success': 'تم تأكيد المستخدم بنجاح!',
  'settings.confirm.error': 'خطأ في تأكيد المستخدم',
  'settings.form.required': 'يرجى ملء جميع الحقول المطلوبة',
  'settings.stats.total': 'إجمالي المستخدمين',
  'settings.stats.admins': 'المديرين',
  'settings.stats.technicians': 'الفنيين',
  'settings.stats.unconfirmed': 'غير مؤكدين',

  // Work Orders
  'workorder.title': 'أمر العمل',
  'workorder.subtitle': 'إدارة أوامر العمل',
  'workorder.description': 'الوصف',
  'workorder.creation_date': 'تاريخ الإنشاء',
  'workorder.start_date': 'تاريخ البداية',
  'workorder.end_date': 'تاريخ الانتهاء',
  'workorder.status': 'الحالة',
  'workorder.technician': 'الفني',
  'workorder.components': 'المكونات',
  'workorder.status.pending': 'في الانتظار',
  'workorder.status.in_progress': 'قيد التنفيذ',
  'workorder.status.completed': 'مكتمل',
  'workorder.status.cancelled': 'ملغي',
  'workorder.generate': 'إنشاء أمر عمل',
  'workorder.close': 'إغلاق أمر العمل',
  'workorder.select_technician': 'اختر فنياً',
  'workorder.search_components': 'البحث عن المكونات...',
  'workorder.add_component': 'إضافة مكون',
  'workorder.remove_component': 'إزالة',
  'workorder.success': 'تمت العملية بنجاح!',
  'workorder.error': 'حدث خطأ',
  'workorder.description.placeholder': 'صف الأعمال المطلوب تنفيذها...',
  'workorder.select_components': 'اختر المكونات',
  'workorder.form.required': 'يرجى ملء جميع الحقول المطلوبة',

  // Dashboard
  'dashboard.title': 'لوحة التحكم',
  'dashboard.subtitle': 'نظرة عامة على الأنشطة',
  'dashboard.welcome': 'مرحباً بك في لوحة التحكم',

  // Profile
  'profile.title': 'ملفي الشخصي',
  'profile.subtitle': 'إدارة الملف الشخصي للمستخدم',
  'profile.edit': 'تعديل الملف الشخصي',
  'profile.save': 'حفظ',
  'profile.cancel': 'إلغاء',
  'profile.firstName': 'الاسم الأول',
  'profile.lastName': 'اسم العائلة',
  'profile.email': 'البريد الإلكتروني',
  'profile.phone': 'الهاتف',
  'profile.address': 'العنوان',
  'profile.role': 'الدور',
  'profile.loading': 'جاري تحميل الملف الشخصي...',
  'profile.error': 'خطأ في تحميل الملف الشخصي',
  'profile.success': 'تم تحديث الملف الشخصي بنجاح',
  'profile.personal_info': 'المعلومات الشخصية',
  'profile.contact_info': 'معلومات الاتصال',
  'profile.account_info': 'معلومات الحساب',
  'profile.firstName.placeholder': 'اسمك الأول',
  'profile.lastName.placeholder': 'اسم العائلة',
  'profile.phone.placeholder': '+966 50 123 4567',
  'profile.address.placeholder': '123 شارع الملك فهد، الرياض 12345',

  // Authentication
  'auth.login': 'تسجيل الدخول',
  'auth.register': 'التسجيل',
  'auth.secure_login': 'تسجيل دخول آمن',
  'auth.email': 'عنوان البريد الإلكتروني',
  'auth.password': 'كلمة المرور',
  'auth.logging_in': 'جاري تسجيل الدخول...',
  'auth.login_button': 'تسجيل الدخول',
  'auth.secure_ssl': 'اتصال SSL آمن',
  'auth.email': 'البريد الإلكتروني',
  'auth.password': 'كلمة المرور',
  'auth.firstName': 'الاسم الأول',
  'auth.lastName': 'اسم العائلة',
  'auth.role': 'الدور',
  'auth.phone': 'الهاتف',
  'auth.address': 'العنوان',
  'auth.login.title': 'تسجيل دخول آمن',
  'auth.login.subtitle': '🏢 منصة ساجيمكوم',
  'auth.login.button': '🚀 تسجيل الدخول',
  'auth.register.title': 'إنشاء حساب',
  'auth.register.subtitle': '🏢 انضم إلى منصة ساجيمكوم',
  'auth.register.button': '🚀 إنشاء حساب',
  'auth.register.success': 'تم إنشاء الحساب بنجاح!',
  'auth.register.hasAccount': 'لديك حساب بالفعل؟',
  'auth.ssl': '🔒 اتصال SSL آمن',

  // Work Orders
  'workOrder.title': 'أمر العمل',
  'workOrder.subtitle': 'إدارة أوامر العمل',
  'workOrder.description': '📝 الوصف',
  'workOrder.dateCreation': '📅 تاريخ الإنشاء',
  'workOrder.dateDebut': '🚀 تاريخ البداية',
  'workOrder.dateFin': '🏁 تاريخ الانتهاء',
  'workOrder.status': '📊 الحالة',
  'workOrder.technician': '👨‍🔧 الفني',
  'workOrder.components': '🔧 المكونات',
  'workOrder.generate': 'إنشاء أمر عمل',
  'workOrder.close': 'إغلاق أمر العمل',
  'workOrder.search': 'البحث عن المكونات...',
  'workOrder.instruction': 'اكتب للبحث واختيار المكونات',
  'workOrder.success': 'تمت العملية بنجاح!',
  'workOrder.error': 'حدث خطأ',
  'workOrder.list.title': 'قائمة أوامر العمل',
  'workOrder.list.subtitle': 'إدارة ومتابعة أوامر العمل',

  // Common
  'common.loading': 'جاري التحميل...',
  'common.error': 'خطأ',
  'common.success': 'نجح',
  'common.cancel': 'إلغاء',
  'common.save': 'حفظ',
  'common.delete': 'حذف',
  'common.edit': 'تعديل',
  'common.add': 'إضافة',
  'common.search': 'بحث',
  'common.filter': 'تصفية',
  'common.sort': 'ترتيب',
  'common.actions': 'الإجراءات',
  'common.status': 'الحالة',
  'common.date': 'التاريخ',
  'common.name': 'الاسم',
  'common.email': 'البريد الإلكتروني',
  'common.role': 'الدور',
  'common.phone': 'الهاتف',
  'common.address': 'العنوان',
  'common.description': 'الوصف',
  'common.type': 'النوع',
  'common.priority': 'الأولوية',

  // Languages
  'language.french': 'Français',
  'language.english': 'English',
  'language.arabic': 'العربية',
  'language.select': 'اختر اللغة'
};

// Available languages
const AVAILABLE_LANGUAGES = {
  fr: { name: 'Français', flag: '🇫🇷', translations: frenchTranslations },
  en: { name: 'English', flag: '🇺🇸', translations: englishTranslations },
  ar: { name: 'العربية', flag: '🇸🇦', translations: arabicTranslations }
};

// Language Provider Component
export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('fr'); // Default to French
  const [translations, setTranslations] = useState(frenchTranslations);
  const [isLoading, setIsLoading] = useState(false);

  // Load saved language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('sagemcom_language');
    if (savedLanguage && AVAILABLE_LANGUAGES[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
      setTranslations(AVAILABLE_LANGUAGES[savedLanguage].translations);
    }
  }, []);

  // Translation function
  const t = (key, defaultValue = key) => {
    return translations[key] || defaultValue;
  };

  // Change language function
  const changeLanguage = async (languageCode) => {
    if (!AVAILABLE_LANGUAGES[languageCode]) {
      console.warn(`Language ${languageCode} not supported`);
      return;
    }

    setIsLoading(true);
    
    try {
      // For external API translations (if needed)
      // const apiTranslations = await translationService.getTranslations(languageCode);
      
      // Use local translations
      const newTranslations = AVAILABLE_LANGUAGES[languageCode].translations;
      
      setCurrentLanguage(languageCode);
      setTranslations(newTranslations);
      
      // Save to localStorage
      localStorage.setItem('sagemcom_language', languageCode);
      
      // Update document direction for Arabic
      document.documentElement.dir = languageCode === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = languageCode;
      
    } catch (error) {
      console.error('Error changing language:', error);
    } finally {
      setIsLoading(false);
    }
  };

  // Get current language info
  const getCurrentLanguageInfo = () => {
    return AVAILABLE_LANGUAGES[currentLanguage] || AVAILABLE_LANGUAGES.fr;
  };

  // Get available languages list
  const getAvailableLanguages = () => {
    return Object.entries(AVAILABLE_LANGUAGES).map(([code, info]) => ({
      code,
      name: info.name,
      flag: info.flag
    }));
  };

  const contextValue = {
    currentLanguage,
    translations,
    isLoading,
    t,
    changeLanguage,
    getCurrentLanguageInfo,
    getAvailableLanguages,
    availableLanguages: AVAILABLE_LANGUAGES
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;